CREATE TABLE clientes (
    client_id serial PRIMARY KEY,
    client_name varchar(255) NOT NULL,
    years numeric(3,0) NOT NULL,
    email varchar(255) NOT NULL,
    idioma varchar(255) NOT NULL,
    enviromental_score numeric(1,0) NOT NULL,
    transport varchar(50) NOT NULL,
    work_preference varchar(50) NOT NULL,
    place_score numeric(1,0) NOT NULL,
    season varchar(50) NOT NULL,
    size_preference varchar(50) NOT NULL,
    entreteiment boolean NOT NULL,
    salary numeric(10,3) NOT NULL,
    percentaje_home numeric(3,0) NOT NULL,
    interest_variable varchar(50) NOT NULL
);

CREATE TABLE datos (
    city_id serial PRIMARY KEY,
    city_name varchar(255) UNIQUE ,
    languages varchar(50) ,
    pollution decimal ,
    best_mobility_option decimal ,
    work_spaces integer ,
    mountain boolean ,
    beach boolean ,
    c_temp decimal,
    c_rainy_days integer,
    c_population decimal,
    density decimal,
    leisure decimal,
    housing decimal,
    cpi decimal,
    gdp_pc decimal,
    tax_burden decimal,
    crime_rate decimal,
    hdi decimal,
    doing_business decimal,
    freedom decimal,
    life_expectancy decimal
);